### PR TITLE
adds wizard component

### PR DESCRIPTION
**Pull request by gofreddo**
@MacKentoch 

http://angular-formly.com/#/example/integrations/angular-wizard

I added a new component that enables the angular-wizard integration.  I mimic the main control so it is in the same architecture.  I tried to touch the main component as little as possible.  The few changes I made are backwards compatible.

### CODE REVIEW

**Comment by gofreddo** [comment]
I only did en.  I'll add other languages when I have a minute.

**Comment by MacKentoch** [comment]
Awesome!

If I'm not wrong the idea is to offer an alternative to current PREV/NEXT interface?

**Comment by gofreddo** [comment]
It just adds easyforms to a wizard.  It needs to check if the form is valid before allowing it to move on.  It's really basic right now.  I plan on adding to it.

**Comment by MacKentoch** [comment]
Nice!

I'm planing to merge stepway steps to make it even easier and faster.
Your idea to integrate it into a wizard is even more valuable.

Take your time, I'm already grateful for all you've done.

**Pull request merged**
